FROM node:23-alpine AS base

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Set working directory
WORKDIR /app

# Backend development stage
FROM base AS backend-dev
WORKDIR /app
EXPOSE 3001
# Mount volumes, run migrations, and ensure node_modules are available
CMD ["sh", "-c", "cd /app && pnpm install && cd /app/backend && pnpm run pmd && cd /app && pnpm --filter @visarun/backend run dev"]

# webapp development stage
FROM base AS webapp-dev
WORKDIR /app
EXPOSE 5173
# Mount volumes and ensure node_modules are available
CMD ["sh", "-c", "cd /app && pnpm install && pnpm --filter @visarun/webapp run dev -- --host 0.0.0.0"]
