export interface CitizenshipData {
  name: string;
  emoji: string;
  abbreviation: string;
  favourite?: boolean;
}

export const citizenships: CitizenshipData[] = [
  // Popular/Favourite citizenships (commonly used in visa runs)
  { name: 'Russian Federation', emoji: '🇷🇺', abbreviation: 'RU', favourite: true },
  { name: 'United States', emoji: '🇺🇸', abbreviation: 'US', favourite: true },
  { name: 'United Kingdom', emoji: '🇬🇧', abbreviation: 'GB', favourite: true },
  { name: 'Germany', emoji: '🇩🇪', abbreviation: 'DE', favourite: true },
  { name: 'France', emoji: '🇫🇷', abbreviation: 'FR', favourite: true },
  { name: 'Australia', emoji: '🇦🇺', abbreviation: 'AU', favourite: true },
  { name: 'Canada', emoji: '🇨🇦', abbreviation: 'CA', favourite: true },
  { name: 'Japan', emoji: '🇯🇵', abbreviation: 'JP', favourite: true },
  { name: 'South Korea', emoji: '🇰🇷', abbreviation: 'KR', favourite: true },
  { name: 'China', emoji: '🇨🇳', abbreviation: 'CN', favourite: true },

  // All other citizenships (alphabetical order)
  { name: 'Afghanistan', emoji: '🇦🇫', abbreviation: 'AF' },
  { name: 'Albania', emoji: '🇦🇱', abbreviation: 'AL' },
  { name: 'Algeria', emoji: '🇩🇿', abbreviation: 'DZ' },
  { name: 'Andorra', emoji: '🇦🇩', abbreviation: 'AD' },
  { name: 'Angola', emoji: '🇦🇴', abbreviation: 'AO' },
  { name: 'Antigua and Barbuda', emoji: '🇦🇬', abbreviation: 'AG' },
  { name: 'Argentina', emoji: '🇦🇷', abbreviation: 'AR' },
  { name: 'Armenia', emoji: '🇦🇲', abbreviation: 'AM' },
  { name: 'Austria', emoji: '🇦🇹', abbreviation: 'AT' },
  { name: 'Azerbaijan', emoji: '🇦🇿', abbreviation: 'AZ' },
  { name: 'Bahamas', emoji: '🇧🇸', abbreviation: 'BS' },
  { name: 'Bahrain', emoji: '🇧🇭', abbreviation: 'BH' },
  { name: 'Bangladesh', emoji: '🇧🇩', abbreviation: 'BD' },
  { name: 'Barbados', emoji: '🇧🇧', abbreviation: 'BB' },
  { name: 'Belarus', emoji: '🇧🇾', abbreviation: 'BY' },
  { name: 'Belgium', emoji: '🇧🇪', abbreviation: 'BE' },
  { name: 'Belize', emoji: '🇧🇿', abbreviation: 'BZ' },
  { name: 'Benin', emoji: '🇧🇯', abbreviation: 'BJ' },
  { name: 'Bhutan', emoji: '🇧🇹', abbreviation: 'BT' },
  { name: 'Bolivia', emoji: '🇧🇴', abbreviation: 'BO' },
  { name: 'Bosnia and Herzegovina', emoji: '🇧🇦', abbreviation: 'BA' },
  { name: 'Botswana', emoji: '🇧🇼', abbreviation: 'BW' },
  { name: 'Brazil', emoji: '🇧🇷', abbreviation: 'BR' },
  { name: 'Brunei', emoji: '🇧🇳', abbreviation: 'BN' },
  { name: 'Bulgaria', emoji: '🇧🇬', abbreviation: 'BG' },
  { name: 'Burkina Faso', emoji: '🇧🇫', abbreviation: 'BF' },
  { name: 'Burundi', emoji: '🇧🇮', abbreviation: 'BI' },
  { name: 'Cambodia', emoji: '🇰🇭', abbreviation: 'KH' },
  { name: 'Cameroon', emoji: '🇨🇲', abbreviation: 'CM' },
  { name: 'Cape Verde', emoji: '🇨🇻', abbreviation: 'CV' },
  { name: 'Central African Republic', emoji: '🇨🇫', abbreviation: 'CF' },
  { name: 'Chad', emoji: '🇹🇩', abbreviation: 'TD' },
  { name: 'Chile', emoji: '🇨🇱', abbreviation: 'CL' },
  { name: 'Colombia', emoji: '🇨🇴', abbreviation: 'CO' },
  { name: 'Comoros', emoji: '🇰🇲', abbreviation: 'KM' },
  { name: 'Democratic Republic of the Congo', emoji: '🇨🇩', abbreviation: 'CD' },
  { name: 'Republic of the Congo', emoji: '🇨🇬', abbreviation: 'CG' },
  { name: 'Costa Rica', emoji: '🇨🇷', abbreviation: 'CR' },
  { name: 'Croatia', emoji: '🇭🇷', abbreviation: 'HR' },
  { name: 'Cuba', emoji: '🇨🇺', abbreviation: 'CU' },
  { name: 'Cyprus', emoji: '🇨🇾', abbreviation: 'CY' },
  { name: 'Czech Republic', emoji: '🇨🇿', abbreviation: 'CZ' },
  { name: 'Denmark', emoji: '🇩🇰', abbreviation: 'DK' },
  { name: 'Djibouti', emoji: '🇩🇯', abbreviation: 'DJ' },
  { name: 'Dominica', emoji: '🇩🇲', abbreviation: 'DM' },
  { name: 'Dominican Republic', emoji: '🇩🇴', abbreviation: 'DO' },
  { name: 'Netherlands', emoji: '🇳🇱', abbreviation: 'NL' },
  { name: 'East Timor', emoji: '🇹🇱', abbreviation: 'TL' },
  { name: 'Ecuador', emoji: '🇪🇨', abbreviation: 'EC' },
  { name: 'Egypt', emoji: '🇪🇬', abbreviation: 'EG' },
  { name: 'El Salvador', emoji: '🇸🇻', abbreviation: 'SV' },
  { name: 'Equatorial Guinea', emoji: '🇬🇶', abbreviation: 'GQ' },
  { name: 'Eritrea', emoji: '🇪🇷', abbreviation: 'ER' },
  { name: 'Estonia', emoji: '🇪🇪', abbreviation: 'EE' },
  { name: 'Eswatini', emoji: '🇸🇿', abbreviation: 'SZ' },
  { name: 'Ethiopia', emoji: '🇪🇹', abbreviation: 'ET' },
  { name: 'Fiji', emoji: '🇫🇯', abbreviation: 'FJ' },
  { name: 'Finland', emoji: '🇫🇮', abbreviation: 'FI' },
  { name: 'Gabon', emoji: '🇬🇦', abbreviation: 'GA' },
  { name: 'Gambia', emoji: '🇬🇲', abbreviation: 'GM' },
  { name: 'Georgia', emoji: '🇬🇪', abbreviation: 'GE' },
  { name: 'Ghana', emoji: '🇬🇭', abbreviation: 'GH' },
  { name: 'Greece', emoji: '🇬🇷', abbreviation: 'GR' },
  { name: 'Grenada', emoji: '🇬🇩', abbreviation: 'GD' },
  { name: 'Guatemala', emoji: '🇬🇹', abbreviation: 'GT' },
  { name: 'Guinea', emoji: '🇬🇳', abbreviation: 'GN' },
  { name: 'Guinea-Bissau', emoji: '🇬🇼', abbreviation: 'GW' },
  { name: 'Guyana', emoji: '🇬🇾', abbreviation: 'GY' },
  { name: 'Haiti', emoji: '🇭🇹', abbreviation: 'HT' },
  { name: 'Honduras', emoji: '🇭🇳', abbreviation: 'HN' },
  { name: 'Hungary', emoji: '🇭🇺', abbreviation: 'HU' },
  { name: 'Iceland', emoji: '🇮🇸', abbreviation: 'IS' },
  { name: 'India', emoji: '🇮🇳', abbreviation: 'IN' },
  { name: 'Indonesia', emoji: '🇮🇩', abbreviation: 'ID' },
  { name: 'Iran', emoji: '🇮🇷', abbreviation: 'IR' },
  { name: 'Iraq', emoji: '🇮🇶', abbreviation: 'IQ' },
  { name: 'Ireland', emoji: '🇮🇪', abbreviation: 'IE' },
  { name: 'Israel', emoji: '🇮🇱', abbreviation: 'IL' },
  { name: 'Italy', emoji: '🇮🇹', abbreviation: 'IT' },
  { name: 'Ivory Coast', emoji: '🇨🇮', abbreviation: 'CI' },
  { name: 'Jamaica', emoji: '🇯🇲', abbreviation: 'JM' },
  { name: 'Jordan', emoji: '🇯🇴', abbreviation: 'JO' },
  { name: 'Kazakhstan', emoji: '🇰🇿', abbreviation: 'KZ' },
  { name: 'Kenya', emoji: '🇰🇪', abbreviation: 'KE' },
  { name: 'Kiribati', emoji: '🇰🇮', abbreviation: 'KI' },
  { name: 'North Korea', emoji: '🇰🇵', abbreviation: 'KP' },
  { name: 'Kuwait', emoji: '🇰🇼', abbreviation: 'KW' },
  { name: 'Kyrgyzstan', emoji: '🇰🇬', abbreviation: 'KG' },
  { name: 'Laos', emoji: '🇱🇦', abbreviation: 'LA' },
  { name: 'Latvia', emoji: '🇱🇻', abbreviation: 'LV' },
  { name: 'Lebanon', emoji: '🇱🇧', abbreviation: 'LB' },
  { name: 'Lesotho', emoji: '🇱🇸', abbreviation: 'LS' },
  { name: 'Liberia', emoji: '🇱🇷', abbreviation: 'LR' },
  { name: 'Libya', emoji: '🇱🇾', abbreviation: 'LY' },
  { name: 'Liechtenstein', emoji: '🇱🇮', abbreviation: 'LI' },
  { name: 'Lithuania', emoji: '🇱🇹', abbreviation: 'LT' },
  { name: 'Luxembourg', emoji: '🇱🇺', abbreviation: 'LU' },
  { name: 'North Macedonia', emoji: '🇲🇰', abbreviation: 'MK' },
  { name: 'Madagascar', emoji: '🇲🇬', abbreviation: 'MG' },
  { name: 'Malawi', emoji: '🇲🇼', abbreviation: 'MW' },
  { name: 'Malaysia', emoji: '🇲🇾', abbreviation: 'MY' },
  { name: 'Maldives', emoji: '🇲🇻', abbreviation: 'MV' },
  { name: 'Mali', emoji: '🇲🇱', abbreviation: 'ML' },
  { name: 'Malta', emoji: '🇲🇹', abbreviation: 'MT' },
  { name: 'Marshall Islands', emoji: '🇲🇭', abbreviation: 'MH' },
  { name: 'Mauritania', emoji: '🇲🇷', abbreviation: 'MR' },
  { name: 'Mauritius', emoji: '🇲🇺', abbreviation: 'MU' },
  { name: 'Mexico', emoji: '🇲🇽', abbreviation: 'MX' },
  { name: 'Micronesia', emoji: '🇫🇲', abbreviation: 'FM' },
  { name: 'Moldova', emoji: '🇲🇩', abbreviation: 'MD' },
  { name: 'Monaco', emoji: '🇲🇨', abbreviation: 'MC' },
  { name: 'Mongolia', emoji: '🇲🇳', abbreviation: 'MN' },
  { name: 'Montenegro', emoji: '🇲🇪', abbreviation: 'ME' },
  { name: 'Morocco', emoji: '🇲🇦', abbreviation: 'MA' },
  { name: 'Mozambique', emoji: '🇲🇿', abbreviation: 'MZ' },
  { name: 'Myanmar', emoji: '🇲🇲', abbreviation: 'MM' },
  { name: 'Namibia', emoji: '🇳🇦', abbreviation: 'NA' },
  { name: 'Nauru', emoji: '🇳🇷', abbreviation: 'NR' },
  { name: 'Nepal', emoji: '🇳🇵', abbreviation: 'NP' },
  { name: 'New Zealand', emoji: '🇳🇿', abbreviation: 'NZ' },
  { name: 'Nicaragua', emoji: '🇳🇮', abbreviation: 'NI' },
  { name: 'Niger', emoji: '🇳🇪', abbreviation: 'NE' },
  { name: 'Nigeria', emoji: '🇳🇬', abbreviation: 'NG' },
  { name: 'Norway', emoji: '🇳🇴', abbreviation: 'NO' },
  { name: 'Oman', emoji: '🇴🇲', abbreviation: 'OM' },
  { name: 'Pakistan', emoji: '🇵🇰', abbreviation: 'PK' },
  { name: 'Palau', emoji: '🇵🇼', abbreviation: 'PW' },
  { name: 'Palestine', emoji: '🇵🇸', abbreviation: 'PS' },
  { name: 'Panama', emoji: '🇵🇦', abbreviation: 'PA' },
  { name: 'Papua New Guinea', emoji: '🇵🇬', abbreviation: 'PG' },
  { name: 'Paraguay', emoji: '🇵🇾', abbreviation: 'PY' },
  { name: 'Peru', emoji: '🇵🇪', abbreviation: 'PE' },
  { name: 'Philippines', emoji: '🇵🇭', abbreviation: 'PH' },
  { name: 'Poland', emoji: '🇵🇱', abbreviation: 'PL' },
  { name: 'Portugal', emoji: '🇵🇹', abbreviation: 'PT' },
  { name: 'Qatar', emoji: '🇶🇦', abbreviation: 'QA' },
  { name: 'Romania', emoji: '🇷🇴', abbreviation: 'RO' },
  { name: 'Rwanda', emoji: '🇷🇼', abbreviation: 'RW' },
  { name: 'Saint Kitts and Nevis', emoji: '🇰🇳', abbreviation: 'KN' },
  { name: 'Saint Lucia', emoji: '🇱🇨', abbreviation: 'LC' },
  { name: 'Saint Vincent and the Grenadines', emoji: '🇻🇨', abbreviation: 'VC' },
  { name: 'Samoa', emoji: '🇼🇸', abbreviation: 'WS' },
  { name: 'San Marino', emoji: '🇸🇲', abbreviation: 'SM' },
  { name: 'São Tomé and Príncipe', emoji: '🇸🇹', abbreviation: 'ST' },
  { name: 'Saudi Arabia', emoji: '🇸🇦', abbreviation: 'SA' },
  { name: 'Senegal', emoji: '🇸🇳', abbreviation: 'SN' },
  { name: 'Serbia', emoji: '🇷🇸', abbreviation: 'RS' },
  { name: 'Seychelles', emoji: '🇸🇨', abbreviation: 'SC' },
  { name: 'Sierra Leone', emoji: '🇸🇱', abbreviation: 'SL' },
  { name: 'Singapore', emoji: '🇸🇬', abbreviation: 'SG' },
  { name: 'Slovakia', emoji: '🇸🇰', abbreviation: 'SK' },
  { name: 'Slovenia', emoji: '🇸🇮', abbreviation: 'SI' },
  { name: 'Solomon Islands', emoji: '🇸🇧', abbreviation: 'SB' },
  { name: 'Somalia', emoji: '🇸🇴', abbreviation: 'SO' },
  { name: 'South Africa', emoji: '🇿🇦', abbreviation: 'ZA' },
  { name: 'South Sudan', emoji: '🇸🇸', abbreviation: 'SS' },
  { name: 'Spain', emoji: '🇪🇸', abbreviation: 'ES' },
  { name: 'Sri Lanka', emoji: '🇱🇰', abbreviation: 'LK' },
  { name: 'Sudan', emoji: '🇸🇩', abbreviation: 'SD' },
  { name: 'Suriname', emoji: '🇸🇷', abbreviation: 'SR' },
  { name: 'Sweden', emoji: '🇸🇪', abbreviation: 'SE' },
  { name: 'Switzerland', emoji: '🇨🇭', abbreviation: 'CH' },
  { name: 'Syria', emoji: '🇸🇾', abbreviation: 'SY' },
  { name: 'Taiwan', emoji: '🇹🇼', abbreviation: 'TW' },
  { name: 'Tajikistan', emoji: '🇹🇯', abbreviation: 'TJ' },
  { name: 'Tanzania', emoji: '🇹🇿', abbreviation: 'TZ' },
  { name: 'Thailand', emoji: '🇹🇭', abbreviation: 'TH' },
  { name: 'Togo', emoji: '🇹🇬', abbreviation: 'TG' },
  { name: 'Tonga', emoji: '🇹🇴', abbreviation: 'TO' },
  { name: 'Trinidad and Tobago', emoji: '🇹🇹', abbreviation: 'TT' },
  { name: 'Tunisia', emoji: '🇹🇳', abbreviation: 'TN' },
  { name: 'Turkey', emoji: '🇹🇷', abbreviation: 'TR' },
  { name: 'Turkmenistan', emoji: '🇹🇲', abbreviation: 'TM' },
  { name: 'Tuvalu', emoji: '🇹🇻', abbreviation: 'TV' },
  { name: 'Uganda', emoji: '🇺🇬', abbreviation: 'UG' },
  { name: 'Ukraine', emoji: '🇺🇦', abbreviation: 'UA' },
  { name: 'United Arab Emirates', emoji: '🇦🇪', abbreviation: 'AE' },
  { name: 'Uruguay', emoji: '🇺🇾', abbreviation: 'UY' },
  { name: 'Uzbekistan', emoji: '🇺🇿', abbreviation: 'UZ' },
  { name: 'Vanuatu', emoji: '🇻🇺', abbreviation: 'VU' },
  { name: 'Vatican City', emoji: '🇻🇦', abbreviation: 'VA' },
  { name: 'Venezuela', emoji: '🇻🇪', abbreviation: 'VE' },
  { name: 'Vietnam', emoji: '🇻🇳', abbreviation: 'VN' },
  { name: 'Yemen', emoji: '🇾🇪', abbreviation: 'YE' },
  { name: 'Zambia', emoji: '🇿🇲', abbreviation: 'ZM' },
  { name: 'Zimbabwe', emoji: '🇿🇼', abbreviation: 'ZW' },
];
