export interface CitizenshipData {
  name: string;
  favourite?: boolean;
}

export const citizenships: CitizenshipData[] = [
  // Popular/Favourite citizenships (commonly used in visa runs)
  { name: 'Russian', favourite: true },
  { name: 'American', favourite: true },
  { name: 'British', favourite: true },
  { name: 'German', favourite: true },
  { name: 'French', favourite: true },
  { name: 'Australian', favourite: true },
  { name: 'Canadian', favourite: true },
  { name: 'Japanese', favourite: true },
  { name: 'South Korean', favourite: true },
  { name: 'Chinese', favourite: true },

  // All other citizenships (alphabetical order)
  { name: 'Afghan' },
  { name: 'Albanian' },
  { name: 'Algerian' },
  { name: 'Andorran' },
  { name: 'Angolan' },
  { name: 'Antiguan and Barbudan' },
  { name: 'Argentine' },
  { name: 'Armenian' },
  { name: 'Austrian' },
  { name: 'Azerbaijani' },
  { name: 'Bahamian' },
  { name: 'Bahraini' },
  { name: 'Bangladeshi' },
  { name: 'Barbadian' },
  { name: 'Belarusian' },
  { name: 'Belgian' },
  { name: 'Belizean' },
  { name: 'Beninese' },
  { name: 'Bhutanese' },
  { name: 'Bolivian' },
  { name: 'Bosnian and Herzegovinian' },
  { name: 'Botswanan' },
  { name: 'Brazilian' },
  { name: 'Bruneian' },
  { name: 'Bulgarian' },
  { name: 'Burkinabé' },
  { name: 'Burundian' },
  { name: 'Cambodian' },
  { name: 'Cameroonian' },
  { name: 'Cape Verdean' },
  { name: 'Central African' },
  { name: 'Chadian' },
  { name: 'Chilean' },
  { name: 'Colombian' },
  { name: 'Comoran' },
  { name: 'Congolese (DRC)' },
  { name: 'Congolese (Republic)' },
  { name: 'Costa Rican' },
  { name: 'Croatian' },
  { name: 'Cuban' },
  { name: 'Cypriot' },
  { name: 'Czech' },
  { name: 'Danish' },
  { name: 'Djiboutian' },
  { name: 'Dominican (Commonwealth)' },
  { name: 'Dominican (Republic)' },
  { name: 'Dutch' },
  { name: 'East Timorese' },
  { name: 'Ecuadorian' },
  { name: 'Egyptian' },
  { name: 'Salvadoran' },
  { name: 'Equatorial Guinean' },
  { name: 'Eritrean' },
  { name: 'Estonian' },
  { name: 'Eswatini' },
  { name: 'Ethiopian' },
  { name: 'Fijian' },
  { name: 'Finnish' },
  { name: 'Gabonese' },
  { name: 'Gambian' },
  { name: 'Georgian' },
  { name: 'Ghanaian' },
  { name: 'Greek' },
  { name: 'Grenadian' },
  { name: 'Guatemalan' },
  { name: 'Guinean' },
  { name: 'Guinea-Bissauan' },
  { name: 'Guyanese' },
  { name: 'Haitian' },
  { name: 'Honduran' },
  { name: 'Hungarian' },
  { name: 'Icelandic' },
  { name: 'Indian' },
  { name: 'Indonesian' },
  { name: 'Iranian' },
  { name: 'Iraqi' },
  { name: 'Irish' },
  { name: 'Israeli' },
  { name: 'Italian' },
  { name: 'Ivorian' },
  { name: 'Jamaican' },
  { name: 'Jordanian' },
  { name: 'Kazakhstani' },
  { name: 'Kenyan' },
  { name: 'Kiribati' },
  { name: 'North Korean' },
  { name: 'Kuwaiti' },
  { name: 'Kyrgyzstani' },
  { name: 'Laotian' },
  { name: 'Latvian' },
  { name: 'Lebanese' },
  { name: 'Lesothan' },
  { name: 'Liberian' },
  { name: 'Libyan' },
  { name: 'Liechtensteiner' },
  { name: 'Lithuanian' },
  { name: 'Luxembourgish' },
  { name: 'Macedonian' },
  { name: 'Malagasy' },
  { name: 'Malawian' },
  { name: 'Malaysian' },
  { name: 'Maldivian' },
  { name: 'Malian' },
  { name: 'Maltese' },
  { name: 'Marshallese' },
  { name: 'Mauritanian' },
  { name: 'Mauritian' },
  { name: 'Mexican' },
  { name: 'Micronesian' },
  { name: 'Moldovan' },
  { name: 'Monégasque' },
  { name: 'Mongolian' },
  { name: 'Montenegrin' },
  { name: 'Moroccan' },
  { name: 'Mozambican' },
  { name: 'Burmese' },
  { name: 'Namibian' },
  { name: 'Nauruan' },
  { name: 'Nepalese' },
  { name: 'New Zealand' },
  { name: 'Nicaraguan' },
  { name: 'Nigerien' },
  { name: 'Nigerian' },
  { name: 'Norwegian' },
  { name: 'Omani' },
  { name: 'Pakistani' },
  { name: 'Palauan' },
  { name: 'Palestinian' },
  { name: 'Panamanian' },
  { name: 'Papua New Guinean' },
  { name: 'Paraguayan' },
  { name: 'Peruvian' },
  { name: 'Filipino' },
  { name: 'Polish' },
  { name: 'Portuguese' },
  { name: 'Qatari' },
  { name: 'Romanian' },
  { name: 'Rwandan' },
  { name: 'Saint Kitts and Nevis' },
  { name: 'Saint Lucian' },
  { name: 'Saint Vincent and the Grenadines' },
  { name: 'Samoan' },
  { name: 'San Marinese' },
  { name: 'São Tomé and Príncipe' },
  { name: 'Saudi Arabian' },
  { name: 'Senegalese' },
  { name: 'Serbian' },
  { name: 'Seychellois' },
  { name: 'Sierra Leonean' },
  { name: 'Singaporean' },
  { name: 'Slovak' },
  { name: 'Slovenian' },
  { name: 'Solomon Islander' },
  { name: 'Somali' },
  { name: 'South African' },
  { name: 'South Sudanese' },
  { name: 'Spanish' },
  { name: 'Sri Lankan' },
  { name: 'Sudanese' },
  { name: 'Surinamese' },
  { name: 'Swedish' },
  { name: 'Swiss' },
  { name: 'Syrian' },
  { name: 'Taiwanese' },
  { name: 'Tajikistani' },
  { name: 'Tanzanian' },
  { name: 'Thai' },
  { name: 'Togolese' },
  { name: 'Tongan' },
  { name: 'Trinidadian and Tobagonian' },
  { name: 'Tunisian' },
  { name: 'Turkish' },
  { name: 'Turkmen' },
  { name: 'Tuvaluan' },
  { name: 'Ugandan' },
  { name: 'Ukrainian' },
  { name: 'Emirati' },
  { name: 'Uruguayan' },
  { name: 'Uzbekistani' },
  { name: 'Vanuatuan' },
  { name: 'Vatican' },
  { name: 'Venezuelan' },
  { name: 'Vietnamese' },
  { name: 'Yemeni' },
  { name: 'Zambian' },
  { name: 'Zimbabwean' },
];
