#!/bin/sh
# visarun/.husky/pre-commit

# Run lint-staged with increased timeout
pnpm lint-staged --concurrent false

# Only run types check if lint-staged succeeds
if [ $? -eq 0 ]; then
  pnpm types
fi
